# Generated by Django 4.2.7 on 2024-01-10 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_alter_classroom_options_alter_enrollment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['-date_updated'], 'verbose_name_plural': 'Classrooms'},
        ),
    ]
