# Generated by Django 4.2.7 on 2024-01-10 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_alter_classroom_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='semester',
        ),
    ]
