# Generated by Django 4.2.7 on 2024-01-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_remove_classroom_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
