# Generated by Django 4.2.7 on 2024-01-15 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_alter_activity_basic_config_points_and_more'),
        ('classroom', '0007_alter_enrollment_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='activities',
            field=models.ManyToManyField(blank=True, null=True, to='activity.activity'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='classroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom'),
            preserve_default=False,
        ),
    ]
