# Generated by Django 4.2.7 on 2024-01-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_alter_activity_basic_config_points_and_more'),
        ('classroom', '0008_alter_enrollment_activities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='activities',
            field=models.ManyToManyField(blank=True, to='activity.activity'),
        ),
    ]
