# Generated by Django 4.2.7 on 2024-01-07 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BaseActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DecimalField(decimal_places=2, max_digits=3)),
                ('answer_key', models.TextField(blank=True, null=True)),
                ('training_task', models.FileField(upload_to='', verbose_name=models.FileField(upload_to='training-tasks/'))),
                ('testing_task', models.FileField(upload_to='', verbose_name=models.FileField(upload_to='training-tasks/'))),
                ('max_physical_points', models.PositiveIntegerField()),
                ('max_basic_config_points', models.PositiveIntegerField()),
                ('max_ip_points', models.PositiveIntegerField()),
                ('max_routing_points', models.PositiveIntegerField()),
                ('max_other_points', models.PositiveIntegerField()),
                ('time_limit', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activitycategory')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.course')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=50)),
                ('physical_points', models.PositiveIntegerField()),
                ('basic_config_points', models.PositiveIntegerField()),
                ('ip_points', models.PositiveIntegerField()),
                ('routing_points', models.PositiveIntegerField()),
                ('other_points', models.PositiveIntegerField()),
                ('time_spent', models.PositiveIntegerField()),
                ('status', models.CharField(default='open', max_length=50)),
                ('base_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.baseactivity')),
            ],
        ),
    ]
