# Generated by Django 4.2.7 on 2024-01-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='activitycategory',
            options={'verbose_name_plural': 'Activity Categories'},
        ),
        migrations.AlterModelOptions(
            name='baseactivity',
            options={'verbose_name_plural': 'Base Activities'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterField(
            model_name='baseactivity',
            name='number',
            field=models.CharField(max_length=4),
        ),
    ]
