# Generated by Django 4.2.7 on 2024-01-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_activity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseactivity',
            name='name',
            field=models.CharField(default='hehe', max_length=255),
            preserve_default=False,
        ),
    ]
