# Generated by Django 4.2.7 on 2024-01-09 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_activity_projectid_baseactivity_projectid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='projectID',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='baseactivity',
            name='projectID',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
