# Generated by Django 4.2.7 on 2024-01-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_alter_activity_projectid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='hah'),
            preserve_default=False,
        ),
    ]
