# Generated by Django 4.2.7 on 2024-01-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='basic_config_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='ip_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='other_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='physical_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='routing_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='time_spent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
