# Generated by Django 4.2.7 on 2023-11-14 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usercategory'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='evidences',
            field=models.ManyToManyField(blank=True, to='user.evidence'),
        ),
    ]
