# Generated by Django 4.2.7 on 2023-11-14 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_category_alter_customuser_evidences'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evidence',
            options={'verbose_name': 'Evidence', 'verbose_name_plural': 'Evidences'},
        ),
        migrations.AlterModelOptions(
            name='usercategory',
            options={'verbose_name': 'User Category', 'verbose_name_plural': 'User Categories'},
        ),
    ]
