# Generated by Django 4.2.7 on 2023-11-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_evidence_options_alter_usercategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='user/icons/'),
        ),
    ]
