# Generated by Django 4.2.7 on 2023-11-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customuser_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
