# Generated by Django 4.2.7 on 2023-11-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_evidence_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='evidences',
        ),
        migrations.DeleteModel(
            name='Evidence',
        ),
        migrations.AddField(
            model_name='customuser',
            name='evidences',
            field=models.ImageField(blank=True, null=True, upload_to='user/evidences/'),
        ),
    ]
