# Generated by Django 4.2.7 on 2023-11-14 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_customuser_evidences_delete_evidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.usercategory'),
            preserve_default=False,
        ),
    ]
